version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"            # pom.xml is at repository root
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"            # workflows in .github/workflows
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "github-actions"
