# Auto-label files changed by path
# Requires: actions/labeler action in a workflow if you want auto-labeling.
rules:
  docs:
    - "docs/**"
  python:
    - "**/*.py"
  javascript:
    - "**/*.js"
    java:
    - "**/*.java"
