blank_issues_enabled: true
contact_links:
  - name: Project Support
    url: https://github.com/Drive-for-Java/MyCMD/issues/new
    about: For support, questions, or helping contributors get started.
